<?php

class AddbmController extends ControllerBase
{
    protected function initialize()
    {
        $this->tag->setTitle('添加书签');
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function indexAction()
    {

    }

}

