<?php

class ChangepasswordController extends ControllerBase
{
    protected function initialize()
    {
        $this->tag->setTitle('修改密码');
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function indexAction()
    {

    }

    public function changepasswdAction(){
        if($this->request->isPost()){
            $old_passwd = sha1($_POST['old_passwd']);
            $new_passwd = sha1($_POST['new_passwd']);
            $new_passwd2 = sha1($_POST['new_passwd2']);

            if(!$old_passwd or !$new_passwd or !$new_passwd2){
                echo Phalcon\Tag::linkTo('changepassword', '填写不完整，返回重新修改密码');
                exit();
            }
            if ($new_passwd != $new_passwd2){
                echo '新密码两次不一样，请重新填写！<br />';
                echo Phalcon\Tag::linkTo('changepassword', '返回重新修改密码');
                exit();
            }else{
                if($old_passwd == $new_passwd){
                    echo '新旧密码一样，请重新填写！<br />';
                    echo Phalcon\Tag::linkTo('changepassword', '返回重新修改密码');
                    exit();
                }
            }

            $old_user = $this->session->get('username');

            $user = User::findFirst(array(
                'username = :username: AND passwd = :passwd:',
                'bind' => array('username' => $old_user, 'passwd' => $old_passwd)
            ));
            if ($user){
                $user->username = $old_user;
                $user->passwd = $new_passwd;
                $result = $user->save();
                if($result) {
                    $this->session->remove('username');
                    $this->session->destroy();
                    echo Phalcon\Tag::linkTo('index', '密码修改成功，返回重新登录');
                    exit();
                }else{
                    echo Phalcon\Tag::linkTo('changepassword', '密码修改失败，返回重新修改');
                    exit();
                }
            }else{
                echo Phalcon\Tag::linkTo('changepassword', '旧密码错误，返回重新修改');
                exit();
            }
        }
        $this->view->disable();
    }
}

