<?php

class MemberController extends ControllerBase
{
    protected function initialize()
    {
        $this->tag->setTitle('用户');
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function indexAction()
    {
        $username = $_POST['username'];
        $password = $_POST['password'];

        if($username && $password){
            $user = User::findFirst(array(
                "username = :username: AND passwd = :passwd:",
                'bind' => array('username' => $username, 'passwd' => sha1($password))
            ));
            if ($user){
                $this->session->set('flag', 1);
                $this->session->set('username', $username);
//                $_SESSION['username'] = $username;
            }else{
                $this->session->set('flag', 0);
            }
        }else{
            $this->session->set('flag', 0);
        }
    }

    public function addbmAction(){

    }
}

